apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: argocd           # Namespace change kar sakte ho ya default chhod do
  labels:
    app: nginx-app
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80
   

  
