apiversion: v1
kind: Service
metadata:
<<<<<<< HEAD
  name: nginx
=======
  name: nginx
>>>>>>> refs/remotes/origin/main
spec:
  selector:
    app.kubernetes.io/name: argo-nginx
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
<<<<<<< HEAD
      targetPort: 80
=======
      targetPort: 80
  
>>>>>>> refs/remotes/origin/main
